"""superesp.esp32.gen_agri_calib — bake the agri head + its tokenizer calibration
into a C header for the live-sensor firmware, so on-device quantization is
bit-identical to training.

Emits firmware_agri/main/agri_calib.h:
  - AGRI_VMIN[30], AGRI_VMAX[30]  (per-feature, time-major 6 steps x 5 channels)
  - agri_blob[] + agri_blob_len   (the ATOMECL01 head)
  - AGRI_CLASSES[] + AGRI_NEEDS_IRRIGATE (class index that triggers the relay)
"""
from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ART = HERE.parent / "artifacts"
OUT = HERE / "firmware_agri" / "main"
CHANNELS = ["soil_moisture", "air_temp", "humidity", "soil_temp", "leaf_wetness"]


def main():
    tok = json.loads((ART / "agri.tok.json").read_text())
    vmin, vmax = tok["vmin"], tok["vmax"]
    classes = json.loads((ART / "RESULTS.json").read_text())
    agri = next(r for r in classes if r["head"] == "agri")
    names = agri["classes"]
    blob = (ART / "agri.atomecl").read_bytes()
    assert len(vmin) == 30 and len(vmax) == 30, f"expected 30 features, got {len(vmin)}"

    OUT.mkdir(parents=True, exist_ok=True)
    L = ["/* auto-generated by gen_agri_calib.py — agri head + tokenizer calibration */",
         "#ifndef AGRI_CALIB_H", "#define AGRI_CALIB_H", "",
         f"#define AGRI_N_FEAT 30   /* 6 timesteps x 5 channels (time-major) */",
         f"#define AGRI_T 6",
         f"#define AGRI_C 5",
         f"static const float AGRI_VMIN[30] = {{{','.join(f'{v:.6f}f' for v in vmin)}}};",
         f"static const float AGRI_VMAX[30] = {{{','.join(f'{v:.6f}f' for v in vmax)}}};",
         f"static const char* AGRI_CLASSES[{len(names)}] = {{{','.join(chr(34)+n+chr(34) for n in names)}}};",
         f"#define AGRI_N_CLASSES {len(names)}",
         f"#define AGRI_NEEDS_IRRIGATE {names.index('needs_irrigate')}",
         f"#define AGRI_SENSOR_FAULT {names.index('sensor_fault')}",
         f"static const unsigned char agri_blob[] = {{{','.join(str(b) for b in blob)}}};",
         f"static const unsigned int agri_blob_len = {len(blob)};",
         "", "#endif"]
    (OUT / "agri_calib.h").write_text("\n".join(L))
    print(f"wrote {OUT/'agri_calib.h'}: 30 calib pairs, {len(names)} classes, "
          f"needs_irrigate={names.index('needs_irrigate')}, blob {len(blob)}B")


if __name__ == "__main__":
    main()
