"""superesp.esp32.gen_battery — bake all 12 heads into one on-device test battery.

For each head it: loads the shipped ATOMECL01 blob, picks a real test vector,
computes the GOLDEN expected class with the HOST C engine (parity harness, so
golden == what the device must reproduce bit-for-bit), and emits:
  - battery_data.h : all blobs + per-head token vector + expected class + name
  - golden.json    : the same, for the host-side report grader

The battery firmware (battery_main.c) compiles this for BOTH QEMU Cortex-M3 and
ESP-IDF, so the exact firmware logic is validated in emulation before you flash.

Run:  python3 -m superesp.esp32.gen_battery
"""
from __future__ import annotations

import json
import tempfile
from pathlib import Path

from superesp.heads import HEADS
from superesp.framework import parity

ART = Path(__file__).resolve().parents[1] / "artifacts"
OUT = Path(__file__).resolve().parent
N_VEC = 1  # vectors per head (keep the header small + battery fast)


def _carr(name: str, data: bytes) -> str:
    body = ",".join(str(b) for b in data)
    return f"static const unsigned char {name}[] = {{{body}}};\n" \
           f"static const unsigned int {name}_len = {len(data)};\n"


def _fnv1a64(data: bytes) -> int:
    """FNV-1a 64-bit — must match battery_main.c's fnv1a64 exactly."""
    h = 0xcbf29ce484222325
    for b in data:
        h = ((h ^ b) * 0x100000001b3) & 0xFFFFFFFFFFFFFFFF
    return h


def main():
    if not (parity.gcc_available() and parity.atome_c_available()):
        raise SystemExit("need gcc + upstream atome.c to compute golden")
    tmp = Path(tempfile.mkdtemp())
    harness = parity.build_harness(tmp)

    rows = []
    h = ["/* auto-generated by gen_battery.py — all 12 SuperESP heads */",
         "#ifndef SUPERESP_BATTERY_DATA_H", "#define SUPERESP_BATTERY_DATA_H", ""]
    names_c, blobs_c, lens_c, toks_c, ntoks_c, expect_c, ncls_c, fnv_c = \
        [], [], [], [], [], [], [], []

    for i, head in enumerate(HEADS):
        blob_p = ART / f"{head.name}.atomecl"
        if not blob_p.exists():
            print(f"  SKIP {head.name}: no blob (run train_all first)"); continue
        ds = head.loader(seed=0)
        vec = ds.test_ids[0].tolist()
        cls, logits = parity.run_harness(harness, blob_p, vec)  # HOST golden
        blob = blob_p.read_bytes()
        h.append(_carr(f"blob_{i}", blob))
        h.append(f"static const int toks_{i}[] = {{{','.join(map(str, vec))}}};\n")
        names_c.append(f'"{head.name}"'); blobs_c.append(f"blob_{i}")
        lens_c.append(f"blob_{i}_len"); toks_c.append(f"toks_{i}")
        ntoks_c.append(str(len(vec))); expect_c.append(str(cls))
        ncls_c.append(str(ds.n_classes)); fnv_c.append(f"{_fnv1a64(blob)}ULL")
        rows.append({"head": head.name, "expect_class": cls, "n_classes": ds.n_classes,
                     "tokens": vec, "expect_label": ds.class_names[cls]})
        print(f"  {head.name:11s} vec[{len(vec)}] -> golden class {cls} ({ds.class_names[cls]})")

    n = len(rows)
    h.append(f"#define N_HEADS {n}")
    h.append(f"static const char* head_names[N_HEADS] = {{{','.join(names_c)}}};")
    h.append(f"static const unsigned char* head_blobs[N_HEADS] = {{{','.join(blobs_c)}}};")
    h.append(f"static const unsigned int head_blob_lens[N_HEADS] = {{{','.join(lens_c)}}};")
    h.append(f"static const int* head_toks[N_HEADS] = {{{','.join(toks_c)}}};")
    h.append(f"static const int head_ntoks[N_HEADS] = {{{','.join(ntoks_c)}}};")
    h.append(f"static const int head_expect[N_HEADS] = {{{','.join(expect_c)}}};")
    h.append(f"static const int head_nclasses[N_HEADS] = {{{','.join(ncls_c)}}};")
    h.append(f"static const unsigned long long head_fnv[N_HEADS] = {{{','.join(fnv_c)}}};")
    h.append("\n#endif")
    (OUT / "battery_data.h").write_text("\n".join(h))
    (OUT / "golden.json").write_text(json.dumps(rows, indent=2))
    print(f"wrote battery_data.h ({n} heads) + golden.json")


if __name__ == "__main__":
    main()
