#!/usr/bin/env python3
"""scripts/export_to_atome.py — convert a trained AtomeLM checkpoint to
the ATOME01 binary the C99 engine consumes.

Format (matches `atome.h`):

    "ATOME01"                                 (7 bytes magic)
    embed:   scale(f32) + packed trits        (vocab * d_model trits)
    per block (n_layers):
        norm:   gamma(f32 * d) + beta(f32 * d)
        conv:   scale(f32) + packed trits     (d * kernel_size trits)
        ssm:    a_raw(f32*d) + b(f32*d) + c_out(f32*d)
        Wq:     scale(f32) + packed trits     (d_head * d_model trits)
        Wk:     scale(f32) + packed trits     (d_head * d_model trits)
        Wv:     scale(f32) + packed trits     (d_model * d_model trits)
        router: scale(f32) + packed trits     (3 * d_model trits)
    final_norm: gamma(f32 * d) + beta(f32 * d)
    unembed: scale(f32) + packed trits        (vocab * d_model trits)

Trit packing: 4 trits per byte; 00 = 0, 01 = +1, 11 = -1.

The conv kernel is written with its spatial axis flipped, because
PyTorch's F.conv1d is cross-correlation (weight[..., K-1] aligns with
the current position) while the C kernel writes weight[..., 0] at the
current position.
"""
from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

import numpy as np
import torch

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from atome_llm.core.atome_lm import AtomeLM
from atome_llm.core.ternary import absmean_scale, ternary_signs


MAGIC = b"ATOME01"


def pack_trits(trits: np.ndarray) -> bytes:
    """Pack int8 trits {-1, 0, +1} into 2-bit format. 4 trits per byte.

    Encoding: 00 = 0, 01 = +1, 11 = -1.
    """
    flat = trits.flatten().astype(np.int8)
    n = len(flat)
    n_bytes = (n + 3) // 4
    packed = np.zeros(n_bytes, dtype=np.uint8)
    for i in range(n):
        v = flat[i]
        if v == 1:
            code = 0x01
        elif v == -1:
            code = 0x03
        else:
            code = 0x00
        packed[i >> 2] |= (code << ((i & 3) << 1))
    return packed.tobytes()


def write_ternary(f, weight: torch.nn.Parameter) -> int:
    with torch.no_grad():
        trits = ternary_signs(weight).numpy()
        scale = absmean_scale(weight).item()
    payload = struct.pack("<f", scale) + pack_trits(trits)
    f.write(payload)
    return len(payload)


def write_conv(f, conv_module) -> int:
    """Conv weight is (channels, 1, kernel_size). Flip the spatial axis on export."""
    with torch.no_grad():
        w = conv_module.weight.squeeze(1)
        trits = ternary_signs(w).numpy()[:, ::-1].copy()
        scale = absmean_scale(w).item()
    payload = struct.pack("<f", scale) + pack_trits(trits)
    f.write(payload)
    return len(payload)


def write_norm(f, norm: torch.nn.LayerNorm) -> int:
    gamma = norm.weight.detach().numpy().astype(np.float32)
    beta = norm.bias.detach().numpy().astype(np.float32)
    payload = gamma.tobytes() + beta.tobytes()
    f.write(payload)
    return len(payload)


def write_ssm(f, ssm) -> int:
    a = ssm.a_raw.detach().numpy().astype(np.float32)
    b = ssm.b.detach().numpy().astype(np.float32)
    c = ssm.c_out.detach().numpy().astype(np.float32)
    payload = a.tobytes() + b.tobytes() + c.tobytes()
    f.write(payload)
    return len(payload)


def export_model(model: AtomeLM, output: Path, verbose: bool = True) -> dict:
    cfg = model.config
    d, V, dh, ks, n_layers = cfg["d_model"], cfg["vocab_size"], cfg["d_head"], cfg["kernel_size"], cfg["n_layers"]
    top_k = cfg["top_k"]

    total = 0
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("wb") as f:
        f.write(MAGIC)
        total += len(MAGIC)
        total += write_ternary(f, model.embed.weight)
        for layer_idx, block in enumerate(model.blocks):
            if verbose:
                print(f"  block {layer_idx}")
            total += write_norm(f, block.norm)
            total += write_conv(f, block.local)
            total += write_ssm(f, block.state)
            total += write_ternary(f, block.sparse.Wq.weight)
            total += write_ternary(f, block.sparse.Wk.weight)
            total += write_ternary(f, block.sparse.Wv.weight)
            total += write_ternary(f, block.router.proj.weight)
        total += write_norm(f, model.final_norm)
        total += write_ternary(f, model.unembed.weight)

    stats = {
        "total_bytes": total,
        "d_model": d,
        "vocab_size": V,
        "n_layers": n_layers,
        "d_head": dh,
        "kernel_size": ks,
        "n_pathways": 3,
        "top_k": top_k,
    }
    if verbose:
        print(f"exported {total} bytes ({total / 1024:.1f} KB) → {output}")
    return stats


def generate_c_header(stats: dict, output: Path) -> None:
    text = f"""/* Auto-generated by export_to_atome.py — do not edit */
#ifndef ATOME_MODEL_CONFIG_H
#define ATOME_MODEL_CONFIG_H

#define ATOME_D_MODEL    {stats['d_model']}
#define ATOME_MAX_SEQ    32
#define ATOME_N_LAYERS   {stats['n_layers']}
#define ATOME_N_PATHWAYS {stats['n_pathways']}
#define ATOME_VOCAB_SIZE {stats['vocab_size']}
#define ATOME_D_HEAD     {stats['d_head']}
#define ATOME_KERNEL_SIZE {stats['kernel_size']}
#define ATOME_TOP_K      {stats['top_k']}

#endif /* ATOME_MODEL_CONFIG_H */
"""
    output.write_text(text)
    print(f"generated config header: {output}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--checkpoint", type=Path, required=True)
    ap.add_argument("--output", type=Path, required=True)
    ap.add_argument("--header", action="store_true")
    args = ap.parse_args()

    state = torch.load(args.checkpoint, map_location="cpu", weights_only=True)
    cfg = state["config"]
    model = AtomeLM(**{k: cfg[k] for k in
                       ("vocab_size", "d_model", "n_layers", "d_head", "top_k", "kernel_size")})
    model.load_state_dict(state["state_dict"])
    model.eval()

    stats = export_model(model, args.output)
    if args.header:
        header_path = args.output.with_suffix(".h")
        generate_c_header(stats, header_path)


if __name__ == "__main__":
    main()
