#!/usr/bin/env python3
"""scripts/run_qemu.py — end-to-end Python ↔ Cortex-M3 firmware parity check.

Pipeline:
  1. Build a small AtomeLM at a fixed config
  2. Export it to model.atome
  3. xxd -i model.atome > model_data.h           (bake the blob into a C array)
  4. make -C c_engine/targets/cortex-m3 firmware.elf
  5. qemu-system-arm -M mps2-an385 -nographic -semihosting -kernel firmware.elf
  6. Parse logits from stdout
  7. Run the same input through Python AtomeLM
  8. Compare and report max |Δ|

If `arm-none-eabi-gcc`, `xxd`, or `qemu-system-arm` is missing, the
script exits with a clear message pointing at apt.
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import torch


ROOT = Path(__file__).resolve().parent.parent
CM3_DIR = ROOT / "c_engine" / "targets" / "cortex-m3"
sys.path.insert(0, str(ROOT / "scripts"))


# Fixed test config — matches firmware.c's kTokens and the small parity
# config the host-C parity test also uses.
CONFIG = dict(
    vocab_size=32,
    d_model=16,
    n_layers=2,
    d_head=8,
    top_k=4,
    kernel_size=5,
)
TOKENS = [10, 20, 5, 17, 0, 25]
MAX_SEQ = 8


def _atome_defines(cfg: dict) -> list[str]:
    return [
        f"-DATOME_D_MODEL={cfg['d_model']}",
        f"-DATOME_MAX_SEQ={MAX_SEQ}",
        f"-DATOME_N_LAYERS={cfg['n_layers']}",
        f"-DATOME_N_PATHWAYS=3",
        f"-DATOME_VOCAB_SIZE={cfg['vocab_size']}",
        f"-DATOME_D_HEAD={cfg['d_head']}",
        f"-DATOME_KERNEL_SIZE={cfg['kernel_size']}",
        f"-DATOME_TOP_K={cfg['top_k']}",
    ]


def _check_tools() -> None:
    missing = [t for t in ("arm-none-eabi-gcc", "qemu-system-arm", "xxd")
               if shutil.which(t) is None]
    if missing:
        print(f"error: missing tools: {', '.join(missing)}", file=sys.stderr)
        print("  fix: apt install gcc-arm-none-eabi qemu-system-arm xxd",
              file=sys.stderr)
        raise SystemExit(2)


def _bake_model_data_h(atome_path: Path, header_path: Path) -> None:
    """Run `xxd -i model.atome` and write the result to header_path,
    renaming xxd's symbol to the firmware-expected `model_atome[]`."""
    proc = subprocess.run(
        ["xxd", "-i", "-n", "model_atome", str(atome_path)],
        capture_output=True, text=True, check=True,
    )
    header_path.write_text(proc.stdout)


def _build_firmware(defines: list[str]) -> Path:
    # Remove only the build artifacts, not the baked model header
    # (the header was just generated by the caller).
    for fn in ("startup.o", "firmware.o", "atome.o",
               "firmware.elf", "firmware.map"):
        (CM3_DIR / fn).unlink(missing_ok=True)
    proc = subprocess.run(
        ["make", "-C", str(CM3_DIR),
         f"ATOME_DEFINES={' '.join(defines)}",
         "firmware.elf"],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        sys.stderr.write(proc.stdout)
        sys.stderr.write(proc.stderr)
        raise SystemExit("firmware build failed")
    print(proc.stdout, end="")
    return CM3_DIR / "firmware.elf"


def _run_qemu(elf: Path, timeout_s: float = 30.0) -> str:
    """Run firmware on QEMU MPS2-AN385, return captured stdout."""
    proc = subprocess.run(
        ["qemu-system-arm", "-M", "mps2-an385", "-nographic",
         "-semihosting", "-kernel", str(elf)],
        capture_output=True, text=True, timeout=timeout_s,
    )
    # qemu writes semihosted output to stdout; combine in case
    out = proc.stdout
    if proc.returncode != 0:
        sys.stderr.write(out)
        sys.stderr.write(proc.stderr)
        raise SystemExit(f"qemu exited with {proc.returncode}")
    return out


def _parse_logits(text: str, vocab: int) -> torch.Tensor:
    nums: list[float] = []
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            nums.append(float(line))
        except ValueError:
            # Skip non-float lines (banners, semihosting noise)
            continue
    if len(nums) < vocab:
        raise SystemExit(
            f"only got {len(nums)} logits from QEMU output; expected {vocab}"
        )
    # Take the first vocab numeric lines (in case anything trails)
    return torch.tensor(nums[:vocab], dtype=torch.float32)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--keep-tmp", action="store_true",
                    help="don't delete the temporary working directory")
    args = ap.parse_args()

    _check_tools()

    import export_to_atome as ex
    from atome_llm.core.atome_lm import AtomeLM

    torch.manual_seed(42)
    model = AtomeLM(**CONFIG)
    model.eval()

    work = Path(tempfile.mkdtemp(prefix="atome_qemu_"))
    print(f"workdir: {work}")
    try:
        atome_bin = work / "model.atome"
        ex.export_model(model, atome_bin, verbose=False)
        print(f"exported {atome_bin.stat().st_size:,} bytes → {atome_bin}")

        header = CM3_DIR / "model_data.h"
        _bake_model_data_h(atome_bin, header)
        print(f"baked {header}")

        elf = _build_firmware(_atome_defines(CONFIG))
        print(f"firmware: {elf}")

        out = _run_qemu(elf)
        c_logits = _parse_logits(out, CONFIG["vocab_size"])

        with torch.no_grad():
            ids = torch.tensor([TOKENS], dtype=torch.long)
            py_logits = model(ids)[0, -1, :]

        diff = (c_logits - py_logits).abs()
        max_d = diff.max().item()
        mean_d = diff.mean().item()
        print(f"\nQEMU Cortex-M3 vs Python AtomeLM logits:")
        print(f"  max |Δ|   = {max_d:.6g}")
        print(f"  mean |Δ|  = {mean_d:.6g}")
        print(f"  C argmax  = {c_logits.argmax().item()}")
        print(f"  Py argmax = {py_logits.argmax().item()}")

        if max_d <= 1e-3 and c_logits.argmax() == py_logits.argmax():
            print("\nPASS — Python ↔ Cortex-M3 firmware parity verified.")
            return 0
        else:
            print("\nFAIL — divergence beyond tolerance.")
            return 1
    finally:
        if not args.keep_tmp:
            shutil.rmtree(work, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
