#!/usr/bin/env python3
"""scripts/run_qemu_tinystories.py — run the TRAINED tinystories Atome
checkpoint on emulated Cortex-M3 (QEMU MPS2-AN385).

Sister script to `run_qemu_gen.py`, but instead of training a tiny
synthetic model on the fly it loads the real `checkpoints/atome_tinystories.pt`
(60.8K params, byte tokenizer, 4 layers, d_model=64), exports it to the
`.atome` blob, bakes it into the gen firmware, and runs it under QEMU
exactly as it would run on a real STM32F103 / RP2040.

Output: the C engine's generated bytes, decoded as UTF-8 alongside the
matching Python generation, plus a DWT-cycles → tokens/sec estimate.
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import torch

ROOT = Path(__file__).resolve().parent.parent
GEN_DIR = ROOT / "c_engine" / "targets" / "cortex-m3-gen"
CKPT = ROOT / "checkpoints" / "atome_tinystories.pt"

sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

DEFAULT_PROMPT = "Once "
DEFAULT_NEW_TOKENS = 32
DEFAULT_MAX_SEQ = 64


def _check_tools() -> None:
    missing = [t for t in ("arm-none-eabi-gcc", "qemu-system-arm", "xxd")
               if shutil.which(t) is None]
    if missing:
        print(f"error: missing tools: {', '.join(missing)}", file=sys.stderr)
        raise SystemExit(2)


def _bake_model(atome_path: Path, header_path: Path) -> None:
    proc = subprocess.run(
        ["xxd", "-i", "-n", "model_atome", str(atome_path)],
        capture_output=True, text=True, check=True,
    )
    header_path.write_text(proc.stdout)


def _bake_prompt(prompt_ids: list[int], header_path: Path) -> None:
    body = ", ".join(str(i) for i in prompt_ids)
    header_path.write_text(
        "/* auto-generated by run_qemu_tinystories.py */\n"
        f"static const int kPrompt[DEMO_PROMPT_LEN] = {{ {body} }};\n"
    )


def _defines(cfg: dict, max_seq: int, prompt_len: int, n_new: int) -> list[str]:
    return [
        f"-DATOME_D_MODEL={cfg['d_model']}",
        f"-DATOME_MAX_SEQ={max_seq}",
        f"-DATOME_N_LAYERS={cfg['n_layers']}",
        f"-DATOME_N_PATHWAYS={cfg.get('n_pathways', 3)}",
        f"-DATOME_VOCAB_SIZE={cfg['vocab_size']}",
        f"-DATOME_D_HEAD={cfg['d_head']}",
        f"-DATOME_KERNEL_SIZE={cfg['kernel_size']}",
        f"-DATOME_TOP_K={cfg['top_k']}",
        f"-DDEMO_PROMPT_LEN={prompt_len}",
        f"-DDEMO_NEW_TOKENS={n_new}",
        "-DATOME_USE_PROMPT_HEADER",
    ]


def _build(defines: list[str]) -> Path:
    for fn in ("startup.o", "firmware.o", "atome.o",
               "firmware.elf", "firmware.map"):
        (GEN_DIR / fn).unlink(missing_ok=True)
    proc = subprocess.run(
        ["make", "-C", str(GEN_DIR),
         f"ATOME_DEFINES={' '.join(defines)}",
         "firmware.elf"],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        sys.stderr.write(proc.stdout); sys.stderr.write(proc.stderr)
        raise SystemExit("gen firmware build failed")
    print(proc.stdout, end="")
    return GEN_DIR / "firmware.elf"


def _run(elf: Path, timeout_s: float = 1800.0) -> str:
    proc = subprocess.run(
        ["qemu-system-arm", "-M", "mps2-an385", "-nographic",
         "-semihosting", "-kernel", str(elf)],
        capture_output=True, text=True, timeout=timeout_s,
    )
    return proc.stdout


def _parse(out: str) -> tuple[list[int], int]:
    tokens: list[int] = []
    cycles = -1
    for line in out.splitlines():
        line = line.strip()
        if line.startswith("TOK "):
            parts = line.split()
            tokens.append(int(parts[2]))
        elif line.startswith("ATOME-GEN-END"):
            for kv in line.split():
                if kv.startswith("total_cycles="):
                    cycles = int(kv.split("=", 1)[1])
    return tokens, cycles


def _decode_bytes(ids: list[int]) -> str:
    return bytes(b & 0xFF for b in ids).decode("utf-8", errors="replace")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--prompt", default=DEFAULT_PROMPT,
                    help="UTF-8 string prompt for the byte tokenizer")
    ap.add_argument("--n-new", type=int, default=DEFAULT_NEW_TOKENS)
    ap.add_argument("--max-seq", type=int, default=DEFAULT_MAX_SEQ)
    ap.add_argument("--mcu-clock-mhz", type=float, default=125.0,
                    help="reference MCU clock for tokens/sec estimate (RP2040=125, STM32F103=72)")
    ap.add_argument("--checkpoint", type=Path, default=CKPT)
    ap.add_argument("--keep-tmp", action="store_true")
    args = ap.parse_args()

    _check_tools()
    if not args.checkpoint.exists():
        print(f"error: checkpoint not found: {args.checkpoint}", file=sys.stderr)
        return 2

    import export_to_atome as ex
    from atome_llm.core.atome_lm import AtomeLM

    state = torch.load(args.checkpoint, map_location="cpu", weights_only=True)
    cfg = state["config"]
    print(f"loaded checkpoint: {args.checkpoint.name}  config={cfg}")

    model = AtomeLM(**{k: cfg[k] for k in
                       ("vocab_size", "d_model", "n_layers", "d_head",
                        "top_k", "kernel_size")})
    model.load_state_dict(state["state_dict"])
    model.eval()

    prompt_ids = list(args.prompt.encode("utf-8"))
    if not prompt_ids:
        print("error: empty prompt", file=sys.stderr); return 2
    if len(prompt_ids) + args.n_new > args.max_seq:
        print(f"error: prompt({len(prompt_ids)}) + n_new({args.n_new}) "
              f"> max_seq({args.max_seq})", file=sys.stderr)
        return 2

    print(f"prompt: {args.prompt!r} → {prompt_ids}  ({len(prompt_ids)} bytes)")
    print(f"will generate {args.n_new} new tokens; ATOME_MAX_SEQ={args.max_seq}")

    work = Path(tempfile.mkdtemp(prefix="atome_qts_"))
    try:
        atome_bin = work / "model.atome"
        ex.export_model(model, atome_bin, verbose=False)
        print(f"exported atome blob: {atome_bin.stat().st_size} bytes")

        _bake_model(atome_bin, GEN_DIR / "model_data.h")
        _bake_prompt(prompt_ids, GEN_DIR / "prompt_data.h")
        elf = _build(_defines(cfg, args.max_seq, len(prompt_ids), args.n_new))

        print("running QEMU mps2-an385 (Cortex-M3)…")
        out = _run(elf)
        tokens, cycles = _parse(out)
        if not tokens:
            sys.stderr.write("no TOK lines parsed; raw output below\n")
            sys.stderr.write(out)
            return 1

        with torch.no_grad():
            py_full = model.generate(
                torch.tensor([prompt_ids], dtype=torch.long),
                n_new_tokens=args.n_new, max_seq=args.max_seq,
            )
            py_tokens = py_full[0, len(prompt_ids):].tolist()

        print()
        print(f"prompt    : {args.prompt!r}")
        print(f"C  cont.  : {_decode_bytes(tokens)!r}")
        print(f"Py cont.  : {_decode_bytes(py_tokens)!r}")
        print(f"C  ids    : {tokens}")
        print(f"Py ids    : {py_tokens}")

        match_len = 0
        for a, b in zip(tokens, py_tokens):
            if a != b:
                break
            match_len += 1
        full_match = match_len == len(tokens) == len(py_tokens)

        print()
        if cycles > 0:
            per_token_cycles = cycles / max(1, len(tokens))
            per_token_us = per_token_cycles / args.mcu_clock_mhz
            tok_per_s = (1e6 / per_token_us) if per_token_us > 0 else 0
            print(f"DWT cycles total      : {cycles:,}")
            print(f"DWT cycles per token  : {per_token_cycles:,.0f}")
            print(f"At {args.mcu_clock_mhz:.0f} MHz                : "
                  f"{per_token_us:.0f} µs/tok → {tok_per_s:.1f} tok/s")
        else:
            print("DWT cycles            : 0  (QEMU mps2-an385 does not model "
                  "the DWT counter; real silicon will report real cycles)")

        print()
        print(f"Token-prefix match    : {match_len}/{len(tokens)} tokens identical to Python")
        if full_match:
            print("PASS — emulated Cortex-M3 matches Python end-to-end.")
            return 0
        if match_len > 0:
            print("PARTIAL — engine ran, first tokens bit-exact; later tokens drift.")
            print("  Likely cause: float-op-order between ARM softfloat and host x86")
            print("  flips argmax on near-tie logits, plus the documented SSM-state")
            print("  persistence bug (atome_dormant_bugs memory). Single-forward")
            print("  parity is bit-exact and is verified by tests/test_qemu_parity.py.")
            return 0
        print("FAIL — no tokens matched Python; engine likely broken on this config.")
        return 1
    finally:
        if not args.keep_tmp:
            shutil.rmtree(work, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
